### PR TITLE
Add support for 'x' in the rgb demos.

### PR DESCRIPTION
**Pull request by ensonic**
Lets make sure the X works out of the box.

### CODE REVIEW

**Comment by FMMT666** [comment]
What is the article number of your device?
It must be different from mine.

The X I have returns "LPX", not "X".
On which OS did you test this?

**Comment by ensonic** [comment]
I have just brought it (a week ago) and I am working under linux. The Sticker on the packaging says 'NOVLPD12" and "Launchpad X".
```shell
> amidi -l
Dir Device    Name
IO  hw:1,0,0  Launchpad X MIDI 1
IO  hw:1,0,1  Launchpad X MIDI 2
```

**Comment by FMMT666** [comment]
Oh yes, indeed.

```
Windoze
  (b'MMSystem', b'LPX MIDI', 1, 0, 0)
  (b'MMSystem', b'MIDIIN2 (LPX MIDI)', 1, 0, 0)
  (b'MMSystem', b'LPX MIDI', 0, 1, 0)
  (b'MMSystem', b'MIDIOUT2 (LPX MIDI)', 0, 1, 0)

macOS
  (b'CoreMIDI', b'Launchpad X LPX DAW Out', 1, 0, 0)
  (b'CoreMIDI', b'Launchpad X LPX MIDI Out', 1, 0, 0)
  (b'CoreMIDI', b'Launchpad X LPX DAW In', 0, 1, 0)
  (b'CoreMIDI', b'Launchpad X LPX MIDI In', 0, 1, 0)

Linux [tm]
  ('ALSA', 'Launchpad X MIDI 1', 0, 1, 0)
  ('ALSA', 'Launchpad X MIDI 1', 1, 0, 0)
  ('ALSA', 'Launchpad X MIDI 2', 0, 1, 0)
  ('ALSA', 'Launchpad X MIDI 2', 1, 0, 0)
```

But just 'x' is not possible, as this conflicts with the Launch Control XL:

```
('ALSA', 'Launch Control XL MIDI 1', 0, 1, 0)
('ALSA', 'Launch Control XL MIDI 1', 1, 0, 0)
('ALSA', 'Launch Control XL MIDI 2', 0, 1, 0)
('ALSA', 'Launch Control XL MIDI 2', 1, 0, 0)
```

So probably something like `launchpad x`, logically ORed with `LPX` might work,
but I would need to check all other OS's and Launchpad variants ...

**Comment by ensonic** [comment]
How is the short name used in the code? Can we use `lpx` for the `launchpad x` and `lcx` for the `launch control x`?

I guess it is this piece of code:
https://github.com/FMMT666/launchpad.py/blob/master/launchpad_py/launchpad.py#L204-L214
aka the ListAll() output, right?

**Comment by FMMT666** [comment]
The name search for the X now looks up "LPX" and "Launchpad X".
Of course only if the LaunchpadLPX class is used.

I also updated all the RGB demos, slightly different, to match the changes in the LPX class.

**Pull request closed without merging**
