### PR TITLE
LPX and MK3 support

### PR DESCRIPTION
**Pull request by NullMember**
I wrote a basic support for LPX and MK3. Most of the functions are same as Launchpad Pro, so no need to override them. On LedCtrlString i've used native text scrolling instead of looping LedCtrlChar function. Are we should write a new function instead of modifying LedCtrlString?

### CODE REVIEW

**Comment by FMMT666** [comment]
Oh great, thanks a lot!

Now, that's a lot of code for one pull request =)
So far, I merged that into a local branch and tested it for the last few ours.
There are some things that either break my local builds or do not work
as expected (I have these things hooked up to my rendering farm).
I could cherry-pick out the stuff I like, but that would make your commits appear
as mine and I truly think that this would be a bit unfair

So here's what I have in mind:

Please ...
- split up the PR in Mk3 and LPX and omit any changes to the demo files (yet)
- the "FlashByCode" method can be fixed by ```self.midi.RawWrite( 145, number, colorcode )```
- ```LedAllOn()``` could be three times faster with Note-On messages (144)
- keep "LedCtrlString()" as it was
- ...

Thanks!

**Comment by NullMember** [comment]
> - split up the PR in Mk3 and LPX and omit any changes to the demo files (yet)  

Fair enough
> - the "FlashByCode" method can be fixed by self.midi.RawWrite( 145, number, colorcode )

I've used SysEx instead of Note On because original pro implementation using SysEx messages. But as I said before I don't want to make decision, I can make them to use Note On messages.

> - `LedAllOn()` could be three times faster with Note-On messages (144)

Sending 100 Note On messages 4 time slower than single SysEx message. I've tested it with timeit library with 1000 iterations and 7 times.
`print(timeit.timeit('lp.LedAllOn(int(random() * 127))', number=1000, globals = {'lp' : lp, 'random' : random}))`
Note On takes ~12 seconds and SysEx takes ~3 seconds. 

> - 'keep "LedCtrlString()" as it was'

If you can suggest a name for native text scrolling function I can write native text scrolling function for Launchpad Pro, X and MK3.

Feel free to close this PR anytime you want. I will make new PRs next days.

**Comment by FMMT666** [comment]
> Sending 100 Note On messages 4 time slower than single SysEx message. I've tested it with timeit library with 1000 iterations and 7 times.

Did you test this with Windoze?
Which PyGame and Python versions, pls?

Also, notice that the time for filling the buffer is not identical to what the
Launchpads actually do. On MacOS, for example the filling of the buffer
is about two times faster that the LED action.

The "3 times faster" was definitely my fault, yes.
I accidentally pulled the SysEx command in the range(100)
loop. Sorry :-)

**Comment by NullMember** [comment]
> Did you test this with Windoze?
Which PyGame and Python versions, pls?

I'm using Windows 10 1909 x64 with Python 3.8.2 and pygame 2.0.0.dev6
I've just measured execution time of 1000 iterations of refreshing 100 leds. I'm definitely sure you're right about 3 times faster argument for updating 1 pad. Saw your tweet on twitter, you opened a whole new window to testing launchpads 😃

**Comment by NullMember** [comment]
https://github.com/FMMT666/launchpad.py/pull/48

For new comments use new PR above

**Pull request closed without merging**
