### PR TITLE
ProMk3 support

### PR DESCRIPTION
**Pull request by NullMember**
This PR adds Pro MK3 support to launchpad.py. This code is experimental, not tested on real hardware. According to [Programmer's Reference Guide](https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/LPP3_prog_ref_guide_200415.pdf) this should work on real hardware.

### CODE REVIEW

**Comment by FMMT666** [comment]
Oh, I missed this, sry!
Actually, the MK3 should also work for the new Pro, but I will check this ...

**Comment by NullMember** [comment]
Only model number in header (12 for LPX, 13 for Mini MK3, 14 for Pro MK3) and valid layout modes changes with each MK3 model.

**Comment by FMMT666** [comment]
Stay tuned, MK3 HW is on its way ...

**Comment by NullMember** [comment]
It's good to hear

**Comment by FMMT666** [comment]
Sorry for the delay, but I had and still have to make some substantial
changes to the Pro and MiniMk3 to make the ProMk3 work.

**Comment by FMMT666** [comment]
So, I can merge this if you remove everything, but the ```LaunchpadProMk3``` class.
If you just pull the current state, add it to the end of the ```launchpad.py``` file:

- pull
- paste
- profit :)

I need to test and add some things to stop it from flooding the message queue.

**Comment by NullMember** [comment]
Opened new PR https://github.com/FMMT666/launchpad.py/pull/60

**Pull request closed without merging**
