### PR TITLE
Move launchpad.py to a Python module (launchpad_py) and add a setup.py installer

### LINKED ISSUE #10: Consider making the project name PEP-8 compliant and importable
launchpad.py is awesome! Unfortunately, publishing scripts that build on top of it is difficult since users would basically have to clone this repo, and copy the dependent scripts into the `launchpad.py` directory (unless I fork & bundle it).

Making the module importable isn't as simple as adding `__init__.py` though, as the name `launchpad.py` is not importable due to the dot in it.

I won't ask that you rename the project, but I did want to point this issue out :)

### PR DESCRIPTION
**Pull request by stewartadam**
Fixes #10 and unblocks #11.

If you don't object to it, I can submit another PR to reorganize & consolidate the documentation available in `__init__.py` (what used to be `launchpad.py`) and `README.md`.

### CODE REVIEW

**Comment by stewartadam** [comment]
Oh, and in the package metadata I chose version v0.9.0 as I saw a prior comment with v0.8.0a.

**Comment by Miserlou** [comment]
Let's get this baby merged!

**Comment by FMMT666** [comment]
Great, thanks!

I made some additional changes (see __init__.py) to maintain compatibility,
for some stuff that we have running here.

Let me know what you think...

**Comment by Miserlou** [comment]
Hooray! Now you can publish so we can close #11 :D

**Comment by FMMT666** [comment]
Will do, but not today...
Regarding that, do you have any idea why

    python setup.py install

only creates an egg file:

    dist-packages/launchpad_py-0.5.0-py2.7.egg

whereas installing from Github, via

    pip2 install git+https://github.com/FMMT666/launchpad.py

creates directories?

    dist-packages/launchpad_py
    dist-packages/launchpad_py-0.5.0.egg-info

**Comment by stewartadam** [comment]
I believe setuptools/setup.py defaults to an egg, but it's not the only installation mode supported and pip defaults to installing the source + egg metadata instead.

BTW, regarding the other commits - you should use`from launchpad_py import local_foo` instead of `import local_foo` in files like `__init__.py` as this will ensure `local_foo` is loaded from your package instead of globally if names conflict, and ensure compatibility with Python 3 as well. This doesn't require any changes to external-facing code / for how users consume your package.

**Pull request merged**
