### PR TITLE
Add easier way to update pro mk3

### PR DESCRIPTION
**Pull request by pnxl**
because yes

### CODE REVIEW

**Comment by FMMT666** [comment]
Could you please move the link to the bottom of the file,
as reference 28?

I might consider merging this then.
With a big warning sign, hehe.  ,( =_=),

**Comment by pnxl** [comment]
So sorry for the late reply!

Where in the bottom, exactly?

**Comment by FMMT666** [comment]
Here, like all the other links:

```
...
[25]: https://www.midifighter.com/
[26]: https://customer.novationmusic.com/en/support/downloads?brand=Novation&product_by_type=510&download_type=all
[27]: https://twitter.com/FMMT666/status/1390806661829386241
```

One can reference them like this:
```
Now with full [Midi Fighter 64][23] support (8/2020).
Finally! Hehe, say hello to the [Mk3 Pro][24] (8/2020)  
And here comes the [Midi Fighter 3D][27] (5/2021)
```

First bracket pair  for the text that shall be highlighted, the second one for the reference, the number.

**Comment by pnxl** [comment]
Ah alright, is this what you mean?

**Comment by FMMT666** [comment]
Exactly, thx!

**Comment by pnxl** [comment]
no problem!

**Pull request merged**
